### ISSUE TITLE
Ekaterina: Week 4, Separation of concerns

### ISSUE THREAD

**Issue by ekaterinaasf** [HackYourFutureBelgium/class-7#94]
#### What is JavaScript?
- [x] [Andrew Mosh](https://www.youtube.com/watch?v=upDLs1sn7g4)
- [x] [Code school](https://www.youtube.com/watch?v=nItSSTwBvSU)
- [x] [MDN: first steps](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript)
- [x] [MDN: JS basics](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics)
- [x] [javascript.info](https://javascript.info/intro)

#### Write some Code
- [x] [Including JS in HTML](https://www.youtube.com/watch?v=AD5hxsFJc4o&list=PL0eyrZgxdwhxNGMWROnaY35NLyEjTqcgB&index=4)
- [x] [Using JS DevTools](https://www.youtube.com/watch?v=sjmyfwESv1g&list=PL0eyrZgxdwhxNGMWROnaY35NLyEjTqcgB&index=5)
- [x] [Rules for writing JS](https://www.youtube.com/watch?v=FdlBtidhAnE&list=PL0eyrZgxdwhxNGMWROnaY35NLyEjTqcgB&index=6)
- [x] [Start learn javascript.online through 2. Strings](https://learnjavascript.online/)

### Calculator-refactor:

- [repository](https://github.com/ekaterinaasf/calculator-refactor)
- [tutorial by mmtuts](https://www.youtube.com/watch?v=qQEYAOPWDzk)
- [x] [README](https://github.com/ekaterinaasf/calculator-refactor/blob/master/README.md)
- [x]  [DOM](https://github.com/ekaterinaasf/calculator-refactor/tree/dom)
- [x]  [styles](https://github.com/ekaterinaasf/calculator-refactor/tree/styles)
- [x]  [listener](https://github.com/ekaterinaasf/calculator-refactor/tree/listener)
- [x]  [handler](https://github.com/ekaterinaasf/calculator-refactor/tree/handler)
- [x] [logic](https://github.com/ekaterinaasf/calculator-refactor/tree/logic)

### Exercises:

- [x] Using user input: [repo](https://github.com/ekaterinaasf/using-user-input)
- [x] FreeCodeCamp JavaScript: [repo](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/)
![Screenshot from 2020-02-04 16-44-23](https://user-images.githubusercontent.com/59531760/73760568-d04dfa00-476d-11ea-8933-a59a25a679fb.png)
![Screenshot from 2020-02-04 16-44-48](https://user-images.githubusercontent.com/59531760/73760587-d6dc7180-476d-11ea-920e-572c69e3dd1a.png)
![Screenshot from 2020-02-04 16-45-15](https://user-images.githubusercontent.com/59531760/73760604-dc39bc00-476d-11ea-87f3-88132b579bcd.png)

- [x] Class exercises: [repo](https://github.com/ekaterinaasf/separation-of-concerns/blob/master/javascript-basics)

> [Follow this link](https://github.com/HackYourFutureBelgium/separation-of-concerns/tree/master/week-1) to find the homework for Week 4.

**Comment by ekaterinaasf** [comment]
I'm blocked with this exercise:
https://github.com/ekaterinaasf/using-user-input/blob/master/1-fill-in-the-blanks/fonting/

Actually, I corrected all parameters I supposed to do, but I cannot understand for which event it should react. I selected a keybord event from the casting example, but it doesn't work. Another idea to add a button and change text parameters by its clicking.

**Comment by ekaterinaasf** [comment]
Also blocked with this exercise:
https://github.com/ekaterinaasf/using-user-input/tree/master/1-fill-in-the-blanks/hex-setter
Do not understand which type of styling we should use. Put it haphazardly.

**Comment by ekaterinaasf** [comment]
Also blocked with 3rd exercise:
https://github.com/ekaterinaasf/using-user-input/tree/master/1-fill-in-the-blanks/patches
Cannot understand the logic. In Readme it's written about buttons, but there are no any buttons at all. Tried to change parameters, but it doesn't work.

**Comment by colevandersWands** [comment]
Patches: good catch. I've updated the readme on our fork of the repo - https://github.com/HackYourFutureBelgium/using-user-input/tree/master/1-fill-in-the-blanks/patches.
I also added a few more test cases that might help you understand what the logic should do

re. styling: do whatever you think makes a nice user interface. these exercises are about fitting all the pieces together, as long as you're understanding how styling fits into exercises it's all good

fonting: look into form events - https://javascript.info/events-change-input

**Comment by ekaterinaasf** [comment]
Thank you Evan. So, I will check them tomorrow. But for the moment I blocked with the calculator refactoring project:
https://github.com/ekaterinaasf/calculator-refactor

Received this error:
handler.js:14 Uncaught ReferenceError: doMath is not defined
    at HTMLButtonElement.calculateHandler (handler.js:14)

**Comment by ekaterinaasf** [comment]
It seems I finished "selecting buttons" and did that I was able to the "patches" exercises. But "patches" still does not work as it has to.

**Comment by inglkruiz** [comment]
@ekaterinaasf Could you configure Github pages on your repo https://github.com/ekaterinaasf/calculator-refactor to see it live and check tests are passing?

**Comment by ekaterinaasf** [comment]
Your site is published at https://ekaterinaasf.github.io/calculator-refactor/
Done

**Comment by ekaterinaasf** [comment]
Here is the page for using-user-input exercises:
https://ekaterinaasf.github.io/using-user-input/

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
